
export const userData = [
        {
          name: 'January',
          "Active User": 2000,
        },
        {
          name: 'February',
          "Active User": 4000,
        },
        {
          name: 'March',
          "Active User": 3500,
        },
        {
          name: 'April',
          "Active User": 2780,
        },
        {
          name: 'May',
          "Active User": 5420,
        },
        {
          name: 'June',
          "Active User": 4243,
        },
        {
          name: 'July',
          "Active User": 4500,
        },
        {
            name: 'August',
            "Active User": 5600,
          },
          {
            name: 'September',
            "Active User": 7532,
          },
          {
            name: 'October',
            "Active User": 3765,
          },
          {
            name: 'November',
            "Active User": 2103,
          },
          {
            name: 'December',
            "Active User": 5630,
          },
      ];

      export const productData = [
        {
          name: 'January',
          "Sales": 2000,
        },
        {
          name: 'February',
          "Sales": 4000,
        },
        {
          name: 'March',
          "Sales": 3500,
        }
      ];

     export const userrows = [
        { id: 1, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 2, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 3, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 4, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 5, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 6, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 7, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 8, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 9, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
        { id: 10, 
            username: 'Jon Snow', 
            avatar:"https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", 
            email: "jon@gmail.com", 
            status:"active", 
            transaction: "$60.00"},
      ];

export const productrows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/1646704/pexels-photo-1646704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    status: "active",
    stock: 10,
    price: "$120",
  },
]